services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin     
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres
    restart: always          
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: changepassword
      POSTGRES_DB: iam
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # PGHBA_CONF_CONTENT: |
      #   host    all             all             0.0.0.0/0               md5    
      # - ./pgdata:/var/lib/postgresql/data
      # host    all             all             0.0.0.0/0               trust
    volumes:                 
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgadmin-data:
  pg-data: